baseURL = "https://blog.invzhi.com/"
languageCode = "en-us"
title = "invzhi"
theme = "hyde"
hasCJKLanguage = true
enableRobotsTXT = true
sectionPagesMenu = "main"

[author]
  name = "invzhi"
  email = "invzhi@protonmail.com"

[taxonomies]
  tag = "tags"

[params]
  description = "know your game."
